[workspace]
members = [
    "game/common/roundo_marionette",
    "game/common/roundo_local_coordinate",
    "game/server/roundo_lifecycle",
    "game/roundo_ecs_entry",
    "roundo_toolbox",
    "roundo_server",
    "roundo_client",
    "roundo_cli",
    "roundo_user_config",
    "game/common/roundo_algorithm",
    "roundo_networking",
    "game/client/roundo_rendering",
    "game/common/roundo_presence", "game/common/roundo_portal", "game/common/roundo_primitive", "roundo_client/roundo_webui", "game/common/roundo_action", "game/common/roundo_mod_loader", "roundo_proc_macros",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = 0
debug-assertions = true
incremental = true
lto = "off"
opt-level = 0
overflow-checks = true
strip = "debuginfo"

[profile.release]
debug = 0
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 3
overflow-checks = false
strip = "debuginfo"

[workspace.dependencies]
anyhow = "1.0"
argh = "0.1"
avian3d = "0.7"
axum = {
    version = "0.8",
    features = ["tokio","multipart","json"],
}
axum-server = {
    version = "0.8",
    features = ["tls-rustls"],
}
bevy = {
    version = "0.19.1",
    default-features = true,
    features = [
        "bevy_dev_tools",
    ]
}
bevy_asset_loader = "0.27"
# bevy_egui = "0.41"
bevy_enhanced_camera = "0.5"
bevy_enhanced_input = "0.26"
# bevy-inspector-egui = "0.37"
# cef = {}
cornucopia = "1"
crossbeam = "0.8"
dotenvy = {
    version = "0.15",
    features = ["cli"],
}
env_logger = "0.11"
jsonwebtoken = { version = "11", features = ["rust_crypto"] }
jwks = "0.5"
log = "0.4"
postcard = {
    version = "1.1",
    features = ["use-std"],
}
quinn = {
    version = "0.11"
}
rand = "0.10"
rand_chacha = "0.10"
reqwest = {
    version = "0.13",
    features = ["default-tls", "json", "multipart",]
}
rustls = "0.23"
rcgen = "0.14"
serde = {
    version = "1",
    features = ["derive"],
}
serde_json = "1"
schemars = "1"
sha2 = "0.11"
sqlx = {
    version = "0.9",
    features = ["derive", "json", "macros", "migrate", "postgres", "runtime-tokio", "time", "uuid",],
}
tokio = {
    version = "1",
    features = ["full"],
}
tokio-rustls = "0.26"
toml = "1.1"
toml_edit = "0.25"
ttf-parser = "0.25"
webpki-roots = "1"
wry = {
    version = "0.56"
}
windows = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"] }
roundo_proc_macros = { path = "roundo_proc_macros" }
# ---
roundo_algorithm = {path = "game/common/roundo_algorithm" }
roundo_cli = { path = "roundo_cli" }
roundo_ecs_entry = { path = "game/roundo_ecs_entry" }
roundo_lifecycle = { path = "game/server/roundo_lifecycle" }
roundo_marionette = { path = "game/common/roundo_marionette" }
roundo_networking = {path = "roundo_networking" }
roundo_rendering = {path = "game/client/roundo_rendering" }
roundo_presence = { path = "game/common/roundo_presence" }
roundo_portal = { path = "game/common/roundo_portal" }
roundo_local_coordinate = { path = "game/common/roundo_local_coordinate" }
roundo_toolbox = { path = "roundo_toolbox" }
roundo_user_config = { path = "roundo_user_config" }
