[package]
name = "roundo_local_coordinate"
version.workspace = true
edition.workspace = true

[dependencies]
avian3d.workspace = true
bevy.workspace = true
log.workspace = true
roundo_algorithm.workspace = true
roundo_networking.workspace = true
roundo_presence.workspace = true
roundo_rendering.workspace = true
roundo_toolbox.workspace = true
serde.workspace = true
[features]
dev = [
    "bevy/debug",
    "bevy/file_watcher",
]
release = [

]
