[package]
name = "roundo_server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "roundo-server"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
log.workspace = true
roundo_cli = { workspace = true, features = ["server"] }
roundo_ecs_entry = { workspace = true, features = ["server"] }
roundo_local_coordinate.workspace = true
roundo_marionette.workspace = true
roundo_networking.workspace = true
roundo_presence.workspace = true
roundo_toolbox.workspace = true
roundo_user_config.workspace = true
serde.workspace = true
sqlx.workspace = true

[dev-dependencies]
toml.workspace = true

[features]
dev = []
release = []
