[package]
name = "roundo_ecs_entry"
version.workspace = true
edition.workspace = true

[features]
client = ["dep:roundo_marionette", "dep:roundo_rendering"]
server = ["dep:avian3d", "dep:roundo_marionette", "dep:roundo_portal"]

[dependencies]
avian3d = { workspace = true, optional = true }
bevy.workspace = true
roundo_marionette = { workspace = true, optional = true }
roundo_local_coordinate.workspace = true
roundo_rendering = { workspace = true, optional = true }
roundo_presence.workspace = true
roundo_portal = { workspace = true, optional = true }
