[package]
name = "roundo_networking"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
axum-server.workspace = true
log.workspace = true
postcard.workspace = true
rand.workspace = true
rcgen.workspace = true
reqwest.workspace = true
roundo_toolbox.workspace = true
rustls.workspace = true
serde.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
webpki-roots.workspace = true
