[package]
name = "roundo_networking"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
postcard.workspace = true
quinn.workspace = true
rcgen.workspace = true
roundo_contracts.workspace = true
rustls.workspace = true
serde.workspace = true
sha2.workspace = true
tokio.workspace = true
webpki-roots.workspace = true
