[slots]
"roundo.disconnected-root" = "main-menu"
"roundo.connected-root" = "hud"
"roundo.main-menu" = "main-menu"
"roundo.server-selection" = "server-selection"
"roundo.connecting" = "connecting"
"roundo.hud" = "hud"
"roundo.settings" = "settings"
"roundo.pause-menu" = "pause-menu"

[[ui]]
name = "main-menu"
project = "main-menu"
entry = "index.html"
interaction_mode = "web-ui"
world_visibility = "hidden"
max_instances = 1

[[ui]]
name = "server-selection"
project = "server-selection"
entry = "index.html"
interaction_mode = "web-ui"
world_visibility = "hidden"
max_instances = 1

[[ui]]
name = "connecting"
project = "connecting"
entry = "index.html"
interaction_mode = "web-ui"
world_visibility = "hidden"
max_instances = 1

[[ui]]
name = "hud"
project = "hud"
entry = "index.html"
interaction_mode = "in-game"
world_visibility = "visible"
max_instances = 1
lifecycle_independent = false
presentation = "exclusive"
layout = "fullscreen"

[[ui]]
name = "settings"
project = "settings"
entry = "index.html"
interaction_mode = "web-ui"
world_visibility = "hidden"
max_instances = 1

[[ui]]
name = "pause-menu"
project = "pause-menu"
entry = "index.html"
interaction_mode = "web-ui"
world_visibility = "visible"
max_instances = 1

[[ui]]
name = "shared"
project = "shared"
entry = "index.html"
interaction_mode = "web-ui"
world_visibility = "hidden"
max_instances = 1

