
[general]
material_name = "example_material"
genuine = 1.0

[[definition]]
property_name = "example_property_0"
# Find union of intervals for same property_name
intervals = [
    [-1.0, 1.0],
    [-2.0, 2.0],
]

[[definition]]
property_name = "example_property_1"
intervals = [
    [10.0, 10.0],
]

