[package]
name = "roundo_client"
version.workspace = true
edition.workspace = true

[[bin]]
name = "roundo-client"
path = "src/main.rs"

[dependencies]
bevy.workspace = true
env_logger.workspace = true
log.workspace = true
roundo_cli.workspace = true
roundo_contracts.workspace = true
roundo_ecs_entry = { workspace = true, features = ["client"] }
roundo_local_coordinate.workspace = true
roundo_marionette.workspace = true
roundo_mod_loader.workspace = true
roundo_networking.workspace = true
roundo_presence.workspace = true
roundo_rendering.workspace = true
roundo_toolbox.workspace = true
roundo_webui.workspace = true
roundo_user_config.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[features]
dev = [
    "roundo_marionette/dev",
]
release = [
    "roundo_marionette/release",
]

[dev-dependencies]
ttf-parser.workspace = true
